Repository openshift/certman-operator, pull requests merged in 2019-05, with the labels that each got.

#27 Add additional printer columns
  deploy/crds/certman_v1alpha1_certificaterequest_crd.yaml
  pkg/apis/certman/v1alpha1/certificaterequest_types.go
  pkg/controller/certificaterequest/certificaterequest_controller.go
  pkg/controller/certificaterequest/dns.go
Labels: approved, lgtm, size/M

#28 Renew/Issue certificate if no data found in secret
  pkg/controller/certificaterequest/certificate.go
  pkg/controller/certificaterequest/certificaterequest_controller.go
  pkg/controller/certificaterequest/renew_certificate.go
  pkg/controller/certificaterequest/update_status.go
Labels: approved, lgtm, size/M

#33 Add certman finalizer to clusterdeployment resource
  pkg/apis/certman/v1alpha1/certificaterequest_types.go
  pkg/controller/certificaterequest/certificaterequest_controller.go
  pkg/controller/certificaterequest/utils.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_delete.go
  pkg/controller/controllerutils/stringutils.go
Labels: approved, lgtm, size/L

#35 Don't process cluster deployment until installed is set to true.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/XS

#36 Read operator config from configmap
  deploy/00_namespace.yaml
  deploy/crds/certman_v1alpha1_certificaterequest_crd.yaml
  pkg/apis/certman/v1alpha1/certificaterequest_types.go
  pkg/apis/certman/v1alpha1/zz_generated.openapi.go
  pkg/controller/certificaterequest/certificaterequest_controller.go
  pkg/controller/certificaterequest/issue_certificate.go
  pkg/controller/certificaterequest/revoke_certificate.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/controllerutils/configmap.go
Labels: approved, size/L

#39 Certman Operator should watch all namespaces
  cmd/manager/main.go
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#40 Fix the Let's Encrypt account secrets namespace
  pkg/controller/certificaterequest/issue_certificate.go
  pkg/controller/certificaterequest/lets_encrypt.go
  pkg/controller/certificaterequest/revoke_certificate.go
Labels: approved, lgtm, size/S

#41 Fix a log message formatting issue
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, size/XS

#42 Fix the secret reference where certs are stored.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, size/XS

#43 Store certificates in secret of type SecretTypeTLS
  README.md
  pkg/controller/certificaterequest/certificate.go
  pkg/controller/certificaterequest/certificaterequest_controller.go
  pkg/controller/certificaterequest/constants.go
  pkg/controller/certificaterequest/issue_certificate.go
  pkg/controller/certificaterequest/lets_encrypt.go
  pkg/controller/certificaterequest/renew_certificate.go
Labels: approved, lgtm, size/M

#45 Updated OWNERS to be consistent with SRE operators
  OWNERS
Labels: approved, lgtm, size/XS

#46 Add core maintainers to reviewer and approver in OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#47 Append "*." prefix to all ingress domain names
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/S

#48 Add operator setup and config instructions
  README.md
Labels: approved, lgtm, size/L

#49 migrate saas repos to gitlab
  hack/app_sre_create_image_catalog.sh
Labels: approved, lgtm, size/XS
