Repository openshift/certman-operator, pull requests merged in 2019-07, with the labels that each got.

#52 Update README with metrics descriptions
  README.md
Labels: approved, lgtm, size/S

#55 added fields to certificate request types
  deploy/crds/certman_v1alpha1_certificaterequest_crd.yaml
  pkg/apis/certman/v1alpha1/certificaterequest_types.go
  pkg/apis/certman/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/certman/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/M

#56 Docs
  OWNERS
  docs/developing.md
Labels: approved, lgtm, size/M

#57 Error handling
  pkg/apis/certman/v1alpha1/certificaterequest_types.go
  pkg/apis/certman/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/certificaterequest/certificaterequest_controller.go
  pkg/controller/certificaterequest/update_status.go
Labels: approved, lgtm, size/M

#59 Added fields for webconsole URL and API URL to certificate creation
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, size/XS
