Repository openshift/certman-operator, pull requests merged in 2019-04, with the labels that each got.

#4 modify certificaterequest to make it cloud-agnostic
  deploy/crds/certman_v1alpha1_certificaterequest_crd.yaml
  pkg/apis/certman/v1alpha1/certificaterequest_types.go
  pkg/apis/certman/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/certman/v1alpha1/zz_generated.openapi.go
Labels: size/L

#6 Create metrics to track number of issued certs for openshift and openshiftapps
  pkg/metrics/metrics.go
Labels: lgtm, size/M

#9 certman operator issue,renew, and revoke
  Gopkg.lock
  deploy/crds/certman_v1alpha1_certificaterequest_cr.yaml
  deploy/crds/certman_v1alpha1_certificaterequest_crd.yaml
  example/certman_v1alpha1_certificaterequest_cr.yaml
  pkg/apis/certman/v1alpha1/certificaterequest_types.go
  pkg/apis/certman/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/certman/v1alpha1/zz_generated.openapi.go
  pkg/awsclient/client.go
  pkg/controller/certificaterequest/certificate.go
  pkg/controller/certificaterequest/certificaterequest_controller.go
  pkg/controller/certificaterequest/cloudflare.go
  pkg/controller/certificaterequest/constants.go
  pkg/controller/certificaterequest/dns.go
  pkg/controller/certificaterequest/issue_certificate.go
  pkg/controller/certificaterequest/lets_encrypt.go
  pkg/controller/certificaterequest/renew_certificate.go
  pkg/controller/certificaterequest/revoke_certificate.go
  pkg/controller/certificaterequest/utils.go
  vendor/github.com/eggsampler/acme/LICENSE
  vendor/github.com/eggsampler/acme/THIRD-PARTY
  vendor/github.com/eggsampler/acme/account.go
  vendor/github.com/eggsampler/acme/acme.go
  vendor/github.com/eggsampler/acme/authorization.go
  vendor/github.com/eggsampler/acme/autocert/autocert.go
  vendor/github.com/eggsampler/acme/certificate.go
  vendor/github.com/eggsampler/acme/challenge.go
  vendor/github.com/eggsampler/acme/examples/autocert/autocert.go
  vendor/github.com/eggsampler/acme/examples/certbot/certbot.go
  vendor/github.com/eggsampler/acme/jws.go
  vendor/github.com/eggsampler/acme/nonce.go
  vendor/github.com/eggsampler/acme/options.go
  vendor/github.com/eggsampler/acme/order.go
  vendor/github.com/eggsampler/acme/problem.go
  vendor/github.com/eggsampler/acme/types.go
Labels: size/XXL

#7 Update Dockerflie add build scripts and add Makefile
  Makefile
  build/Dockerfile
  config/templates/certman-operator-csv-template.yaml
  hack/app_sre_build_deploy.sh
  hack/app_sre_create_image_catalog.sh
  hack/app_sre_pr_check.sh
  hack/generate-operator-bundle.py
  hack/olm-registry/olm-artifacts-template.yaml
Labels: size/L

#10 update description in csv
  README.md
  config/templates/certman-operator-csv-template.yaml
Labels: size/S

#12 Fix Docker path in Makefile
  Makefile
Labels: size/XS

#8 Create metrics to track number of issued certs for openshift and openshiftapps
  cmd/manager/main.go
  pkg/metrics/crt_sh.go
  pkg/metrics/metrics.go
  pkg/metrics/queries.go
Labels: lgtm, size/L

#14 Update deps
  Gopkg.lock
  vendor/github.com/lib/pq/LICENSE.md
  vendor/github.com/lib/pq/array.go
  vendor/github.com/lib/pq/buf.go
  vendor/github.com/lib/pq/conn.go
  vendor/github.com/lib/pq/conn_go18.go
  vendor/github.com/lib/pq/connector.go
  vendor/github.com/lib/pq/copy.go
  vendor/github.com/lib/pq/doc.go
  vendor/github.com/lib/pq/encode.go
  vendor/github.com/lib/pq/error.go
  vendor/github.com/lib/pq/example/listen/doc.go
  vendor/github.com/lib/pq/hstore/hstore.go
  vendor/github.com/lib/pq/notify.go
  vendor/github.com/lib/pq/oid/doc.go
  vendor/github.com/lib/pq/oid/gen.go
  vendor/github.com/lib/pq/oid/types.go
  vendor/github.com/lib/pq/rows.go
  vendor/github.com/lib/pq/scram/scram.go
  vendor/github.com/lib/pq/ssl.go
  vendor/github.com/lib/pq/ssl_permissions.go
  vendor/github.com/lib/pq/ssl_windows.go
  vendor/github.com/lib/pq/url.go
  vendor/github.com/lib/pq/user_posix.go
  vendor/github.com/lib/pq/user_windows.go
  vendor/github.com/lib/pq/uuid.go
Labels: lgtm, size/XXL

#15 Update CertificateRequest status
  pkg/controller/certificaterequest/certificaterequest_controller.go
  pkg/controller/certificaterequest/cloudflare.go
Labels: size/M

#13 [WIP] Update metrics every N hours in a seperate process
  cmd/manager/main.go
  pkg/metrics/metrics.go
Labels: do-not-merge/work-in-progress, size/S

#16 Revert "[WIP] Update metrics every N hours in a seperate process"
  cmd/manager/main.go
  pkg/metrics/metrics.go
Labels: size/S

#17 only make certificate request for RH managed cluster
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: lgtm, size/S

#18 Srep 1143 prep for ci pipeline
  Makefile
  build/Dockerfile
  config/config.go
  project.mk
  standard.mk
Labels: lgtm, size/L

#19 Unit test fixes
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: size/S

#20 Update Makefile docker image
  standard.mk
Labels: lgtm, size/XS

#21 Fix make build target
  Makefile
Labels: lgtm, size/XS

#22 Update metrics every N hours in a seperate process
  cmd/manager/main.go
  pkg/metrics/metrics.go
Labels: lgtm, size/S

#23 Bug fix: spawn UpdateMetrics as its own goroutine
  cmd/manager/main.go
Labels: approved, lgtm, size/XS

#24 Updates the email field CRD for Certificate Request
  OWNERS
  deploy/crds/certman_v1alpha1_certificaterequest_crd.yaml
  pkg/apis/certman/v1alpha1/certificaterequest_types.go
  pkg/apis/certman/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/certman/v1alpha1/zz_generated.openapi.go
  pkg/controller/certificaterequest/certificaterequest_controller.go
  pkg/controller/certificaterequest/constants.go
  pkg/controller/certificaterequest/dns.go
  pkg/controller/certificaterequest/issue_certificate.go
  pkg/controller/certificaterequest/lets_encrypt.go
  pkg/controller/certificaterequest/renew_certificate.go
  pkg/controller/certificaterequest/revoke_certificate.go
  pkg/controller/certificaterequest/update_status.go
  pkg/controller/certificaterequest/utils.go
Labels: approved, lgtm, size/L

#25 Changed from Role/RoleBinding to ClusterRole/ClusterRoleBinding
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
Labels: approved, lgtm, size/S

#26 Don't create certificaterequest if domain list is empty
  README.md
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, size/S
