Repository openshift/certman-operator, pull requests merged in 2019-10, with the labels that each got.

#83 Correct service name to match whats on cluster and in monitoring
  cmd/manager/main.go
Labels: approved, lgtm, size/XS

#84 ensure challenge record deletions
  pkg/controller/certificaterequest/dns.go
Labels: approved, lgtm, size/XS

#85 Adding deletion for test access record after successful write.
  pkg/controller/certificaterequest/dns.go
Labels: approved, lgtm, size/S

#86 Updated OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#88 Detect operator-sdk up local
  cmd/manager/main.go
Labels: approved, lgtm, size/S

#89 Delete after use
  pkg/controller/certificaterequest/issue_certificate.go
Labels: approved, lgtm, size/XS

#90 Delete all acme challenge records
  pkg/awsclient/client.go
  pkg/controller/certificaterequest/dns.go
  pkg/controller/certificaterequest/issue_certificate.go
Labels: approved, lgtm, size/L

#91 Arbitrary versioning bump directly to 1.0.
  version/version.go
Labels: approved, lgtm, size/XS

#92 changing to watching clusterdeployements to Spec.Installed instead of…
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/S

#93 updating csv to match version bump
  config/templates/certman-operator-csv-template.yaml
Labels: approved, lgtm, size/XS
