Repository openshift/certman-operator, pull requests merged in 2019-08, with the labels that each got.

#60 Added metric for runtime of issue certificate function
  cmd/manager/main.go
  pkg/controller/certificaterequest/issue_certificate.go
  pkg/localmetrics/localmetrics.go
Labels: approved, lgtm, size/S

#63 adding 'Status: Success' to finalized certficateRequests
  pkg/controller/certificaterequest/update_status.go
Labels: approved, lgtm, size/XS

#65 Reconcile when cert secret changes
  pkg/controller/certificaterequest/certificaterequest_controller.go
Labels: approved, lgtm, size/XS

#66 reconcile when certificateRequest changes
  pkg/controller/certificaterequest/certificaterequest_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, size/S

#67 code clean for easier readable
  pkg/controller/certificaterequest/certificaterequest_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, size/M

#68 Updating certs with new DNSNames
  pkg/controller/certificaterequest/renew_certificate.go
Labels: approved, lgtm, size/XS

#69 Simplify let's encrypt staging/production env setup
  pkg/controller/certificaterequest/issue_certificate.go
  pkg/controller/certificaterequest/revoke_certificate.go
  pkg/controller/controllerutils/configmap.go
  pkg/leclient/constants.go
  pkg/leclient/lets_encrypt.go
Labels: approved, lgtm, size/L

#70 Update clusterDeployment status as needed
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, size/M

#71 Update setup docs
  README.md
  docs/developing.md
Labels: approved, lgtm, size/M

#72 [SREP-1954] Added comments to all uncommented functions
  cmd/manager/main.go
  pkg/apis/certman/v1alpha1/certificaterequest_types.go
  pkg/awsclient/client.go
  pkg/controller/certificaterequest/certificate.go
  pkg/controller/certificaterequest/certificaterequest_controller.go
  pkg/controller/certificaterequest/cloudflare.go
  pkg/controller/certificaterequest/dns.go
  pkg/controller/certificaterequest/issue_certificate.go
  pkg/controller/certificaterequest/renew_certificate.go
  pkg/controller/certificaterequest/revoke_certificate.go
  pkg/controller/certificaterequest/update_status.go
  pkg/controller/certificaterequest/utils.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_delete.go
  pkg/controller/controllerutils/configmap.go
  pkg/controller/controllerutils/stringutils.go
  pkg/leclient/lets_encrypt.go
Labels: approved, lgtm, size/L

#73 Update to operator-custom-metrics v0.2.1
  Gopkg.lock
  Gopkg.toml
  cmd/manager/main.go
  vendor/github.com/openshift/operator-custom-metrics/pkg/metrics/builder.go
  vendor/github.com/openshift/operator-custom-metrics/pkg/metrics/metrics.go
  vendor/github.com/openshift/operator-custom-metrics/pkg/metrics/metricsconfig.go
  vendor/github.com/openshift/operator-custom-metrics/pkg/metrics/service.go
Labels: approved, lgtm, size/L
