Repository openshift/certman-operator, pull requests merged in 2020-03, with the labels that each got.

#116 Set AWS region from new CR property
  deploy/crds/certman_v1alpha1_certificaterequest_crd.yaml
  pkg/apis/certman/v1alpha1/certificaterequest_types.go
  pkg/apis/certman/v1alpha1/zz_generated.deepcopy.go
  pkg/clients/client.go
  pkg/controller/certificaterequest/certificaterequest_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/M

#118 Added APAC to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#119 adding config for additional api endpoint to default certs, rh-api.cl…
  deploy/operator.yaml
  pkg/controller/certificaterequest/constants.go
Labels: approved, lgtm

#121 Update OWNERS
  OWNERS
Labels: approved, lgtm

#122 Updating Owners
  OWNERS
Labels: approved, lgtm

#123 Use ProjectID from serviceaccount
  pkg/clients/client.go
  pkg/clients/gcp/dns.go
Labels: approved, lgtm

#124 Add a couple minor fixes to make
  standard.mk
Labels: approved, lgtm

#125 Don't hard error on NXDOMAIN
  pkg/controller/certificaterequest/cloudflare.go
  pkg/controller/certificaterequest/constants.go
Labels: approved, lgtm

#126 Update comparison operator
  pkg/controller/certificaterequest/cloudflare.go
Labels: approved, lgtm
