Repository openshift/certman-operator, pull requests merged in 2025-09, with the labels that each got.

#399 Add CLAUDE.md documentation
  CLAUDE.md
Labels: lgtm, approved

#364 SREP-1198: added initial set of unit test for improving coverage
  pkg/clients/aws/route53_test.go
  pkg/clients/azure/dns_test.go
  pkg/localmetrics/localmetrics_test.go
Labels: lgtm, approved, tide/merge-method-squash, ok-to-test, jira/valid-reference

#390 SREP-1222: Test - Prerequisites Certman Operator Installation, Deleted the AWS secret and checked reconciliation in the e2e test.
  .tekton/certman-operator-e2e-pull-request.yaml
  .tekton/certman-operator-e2e-push.yaml
  .tekton/certman-operator-pull-request.yaml
  .tekton/certman-operator-push.yaml
  go.mod
  go.sum
  test/e2e/certman_operator_tests.go
  test/e2e/utils/utils.go
Labels: lgtm, approved, tide/merge-method-squash, jira/valid-reference
