Repository openshift/certman-operator, pull requests merged in 2025-08, with the labels that each got.

#374 boilerplate update 2 3b137befb97d00fb0d5d7318ba4c172cde2884cc
  .tekton/certman-operator-pull-request.yaml
  .tekton/certman-operator-push.yaml
  boilerplate/_data/last-boilerplate-commit
  boilerplate/openshift/golang-osd-e2e/e2e-template.yml
  build/Dockerfile
  build/Dockerfile.olm-registry
  test/e2e/e2e-template.yml
Labels: lgtm, approved

#370 SREP-100 add flags to prevent stuck subscription for certman-operator
  config/config.go
  hack/olm-registry/olm-artifacts-template.yaml
Labels: lgtm, approved

#351 SREP-1072: added initial set of unit tests for improving coverage
  controllers/certificaterequest/certificaterequest_controller_test.go
  controllers/certificaterequest/test_helpers.go
  controllers/certificaterequest/update_status_test.go
  controllers/clusterdeployment/clusterdeployment_controller_test.go
Labels: lgtm, approved, tide/merge-method-squash, ok-to-test, jira/valid-reference

#355 SREP-1222: Deleted the AWS secret and checked reconciliation in the e2e test.
  test/e2e/certman_operator_tests.go
Labels: lgtm, approved, tide/merge-method-squash, jira/valid-reference

#386 SREP-1532 bumping go version to 1.24 and boilerplate for CVE fixes
  .ci-operator.yaml
  boilerplate/_data/backing-image-tag
  boilerplate/_data/last-boilerplate-commit
  boilerplate/openshift/golang-osd-operator/Dockerfile.olm-registry
  build/Dockerfile
  build/Dockerfile.olm-registry
  go.mod
  go.sum
Labels: lgtm, approved

#392 Removing the on-cel-expression to fix the jenkins build
  .tekton/certman-operator-e2e-pull-request.yaml
  .tekton/certman-operator-e2e-push.yaml
  .tekton/certman-operator-pull-request.yaml
  .tekton/certman-operator-push.yaml
Labels: lgtm, approved
